language: android
notifications:
  email:
    recipients:
    - rowlandotienoo@gmail.com
    on_success: always
    on_failure: always
jdk:
- oraclejdk7
- oraclejdk8
android:
  components:
  - tools
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - build-tools-23.0.2
  - android-23
before_install:
- export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
- export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
- export JAVA_HOME=$JAVA8_HOME
- chmod +x gradlew
script: "./gradlew build --stacktrace"
